name = "delay_times"
version = "1.0.0"

description = "A Gleam library for working with delay times."
licences = ["Apache-2.0"]
repository = { type = "github", user = "JosephTLyons", repo = "delay_times_gleam" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
startest = ">= 0.5.0 and < 1.0.0"
